# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry2d_pb2 as geometry2d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x14questnav.protos.data\x1a\x10geometry2d.proto\"n\n\x19ProtobufQuestNavFrameData\x12\x13\n\x0b\x66rame_count\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12)\n\x06pose2d\x18\x03 \x01(\x0b\x32\x19.wpi.proto.ProtobufPose2d\"\xb8\x02\n\x1aProtobufQuestNavDeviceData\x12\x1d\n\x15tracking_lost_counter\x18\x01 \x01(\x05\x12\x1a\n\x12\x63urrently_tracking\x18\x02 \x01(\x08\x12\x17\n\x0f\x62\x61ttery_percent\x18\x03 \x01(\x05\x12\x12\n\nactive_tag\x18\x04 \x01(\x05\x12\x15\n\ractive_layout\x18\x05 \x01(\x05\x12\x14\n\x0c\x61\x63tive_field\x18\x06 \x01(\x05\x12S\n\nsaved_tags\x18\x07 \x03(\x0b\x32?.questnav.protos.data.ProtobufQuestNavDeviceData.SavedTagsEntry\x1a\x30\n\x0eSavedTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\x43\n%gg.questnav.questnav.protos.generated\xaa\x02\x19QuestNav.Protos.Generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%gg.questnav.questnav.protos.generated\252\002\031QuestNav.Protos.Generated'
  _globals['_PROTOBUFQUESTNAVDEVICEDATA_SAVEDTAGSENTRY']._loaded_options = None
  _globals['_PROTOBUFQUESTNAVDEVICEDATA_SAVEDTAGSENTRY']._serialized_options = b'8\001'
  _globals['_PROTOBUFQUESTNAVFRAMEDATA']._serialized_start=54
  _globals['_PROTOBUFQUESTNAVFRAMEDATA']._serialized_end=164
  _globals['_PROTOBUFQUESTNAVDEVICEDATA']._serialized_start=167
  _globals['_PROTOBUFQUESTNAVDEVICEDATA']._serialized_end=479
  _globals['_PROTOBUFQUESTNAVDEVICEDATA_SAVEDTAGSENTRY']._serialized_start=431
  _globals['_PROTOBUFQUESTNAVDEVICEDATA_SAVEDTAGSENTRY']._serialized_end=479
# @@protoc_insertion_point(module_scope)
