# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geometry2d.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'geometry2d.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10geometry2d.proto\x12\twpi.proto\"-\n\x15ProtobufTranslation2d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"#\n\x12ProtobufRotation2d\x12\r\n\x05value\x18\x01 \x01(\x01\"x\n\x0eProtobufPose2d\x12\x35\n\x0btranslation\x18\x01 \x01(\x0b\x32 .wpi.proto.ProtobufTranslation2d\x12/\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.wpi.proto.ProtobufRotation2d\"}\n\x13ProtobufTransform2d\x12\x35\n\x0btranslation\x18\x01 \x01(\x0b\x32 .wpi.proto.ProtobufTranslation2d\x12/\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.wpi.proto.ProtobufRotation2d\"9\n\x0fProtobufTwist2d\x12\n\n\x02\x64x\x18\x01 \x01(\x01\x12\n\n\x02\x64y\x18\x02 \x01(\x01\x12\x0e\n\x06\x64theta\x18\x03 \x01(\x01\"`\n\x13ProtobufRectangle2d\x12)\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x19.wpi.proto.ProtobufPose2d\x12\x0e\n\x06xWidth\x18\x02 \x01(\x01\x12\x0e\n\x06yWidth\x18\x03 \x01(\x01\"d\n\x11ProtobufEllipse2d\x12)\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x19.wpi.proto.ProtobufPose2d\x12\x11\n\txSemiAxis\x18\x02 \x01(\x01\x12\x11\n\tySemiAxis\x18\x03 \x01(\x01\x42\x1a\n\x18\x65\x64u.wpi.first.math.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geometry2d_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030edu.wpi.first.math.proto'
  _globals['_PROTOBUFTRANSLATION2D']._serialized_start=31
  _globals['_PROTOBUFTRANSLATION2D']._serialized_end=76
  _globals['_PROTOBUFROTATION2D']._serialized_start=78
  _globals['_PROTOBUFROTATION2D']._serialized_end=113
  _globals['_PROTOBUFPOSE2D']._serialized_start=115
  _globals['_PROTOBUFPOSE2D']._serialized_end=235
  _globals['_PROTOBUFTRANSFORM2D']._serialized_start=237
  _globals['_PROTOBUFTRANSFORM2D']._serialized_end=362
  _globals['_PROTOBUFTWIST2D']._serialized_start=364
  _globals['_PROTOBUFTWIST2D']._serialized_end=421
  _globals['_PROTOBUFRECTANGLE2D']._serialized_start=423
  _globals['_PROTOBUFRECTANGLE2D']._serialized_end=519
  _globals['_PROTOBUFELLIPSE2D']._serialized_start=521
  _globals['_PROTOBUFELLIPSE2D']._serialized_end=621
# @@protoc_insertion_point(module_scope)
